
DROP TABLE IF EXISTS PRECIOS;

CREATE TABLE PRECIOS (
  ID UUID NOT NULL,
  BRAND_ID INT NOT NULL,
  START_DATE VARCHAR(19) NOT NULL,
  END_DATE VARCHAR(19) NOT NULL,
  PRICE_LIST INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  PRIORITY INT NOT NULL,
  PRICE NUMERIC NOT NULL,
  CURR VARCHAR(3) NOT NULL,
  PRIMARY KEY (ID)
);